# Default properties file

spring:
  profiles:
    active: ${SCOPE_SUFFIX} # Comma-separated list of active profiles. Can be overridden by a command line switch.
  resources:
    add-mappings: false # Whether to enable default resource handling.
  mvc:
    throw-exception-if-no-handler-found: true # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.

server:
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  paths-to-match: /api/v1/fresh-products/inboundorder/**, /api/v1/fresh-products/orders/**, /api/v1/fresh-products/list, /api/v1/fresh-products
#  packages-to-scan: com.mercadolibre.projetointegrador.controller
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true
    path: /swagger-ui.html

app:
  title: projetointegrador
  description: Projeto integrador desenvolvido como desafio final do bootcamp de aceleração
  version: 1.0.0